version: "3"
services:
  web:
    image: dnratthee/dn-shorty:latest
    container_name: dn-shorty-web
    environment:
      - chars=${chars}
      - host=${host}
      - port=${port}
      - db=${db}
      - dbName=${dbName}
    external_links:
      - mongo:mongo
networks:
  default:
    external: true
    name: dnratthee.me